### ISSUE TITLE
Add expando to text posts. Auto hide text initially, and when clicked, show text.

### ISSUE THREAD

**Issue by pauldotknopf** [skimur/skimur#29]
https://skimur.com/s/ideasforskimur/post/d058bacb-836a-e511-929c-5404a632cbf7/it_would_be_nice_if_the_text_of_text_posts_wasnt

**Comment by metalphoenix** [comment]
Do you want this completely collapsed to an expando or do you want a preview showing? Say maybe the first 75 or whatever characters with a "... <read more>" link?

For consistency, use the same expando as planned for images and videos.

For flair, provide an excerpt.

Or do you want both with an option in settings (or per sub) which to display?

**Comment by pauldotknopf** [comment]
Ya, maybe not ellipsize the text, but simply show expandos. Same expando for both text/image/video. I am going to re-title this issue. I think the development on expandos for multi-media should be done on another issue, as I think it will be developed at the same time as we develop exandos within comments/text.

So, the scope of this issue is to show an icon indicating there is text to be show, and when clicked, shows the text. For "text" posts only.

**Comment by pauldotknopf** [comment]
I created #68, which will be specifically for handling embedded media items.
